add_game/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('add_game/', views.add_game, name='add_game'),
    path('update_game/<int:id>/', views.update_game, name='update_game'),
    path('delete_game/<int:id>/', views.delete_game, name='delete_game'),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('library/', include('library.urls')),
    path('games/', include('add_game.urls')),
    path('accounts/', include('allauth.urls')),
]

add_game/models.py
from django.db import models

# Create your models here.

library/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse


class Post(models.Model):
    SHOOTER = 'Shooter'
    ACTION_ADV = 'Action adventure'
    MOBA = 'MOBA'
    RACING = 'Racing'
    SIM = 'Simulation'
    BR = 'Battle Royale'
    RTS = 'Real-time Strategy'
    PUZZLE_PLAT = 'Puzzle Platform'
    SPORTS = 'Sports'
    MMO = 'MMO'
    SINGLE = 'Singleplayer'
    COOP = 'Co-op'
    RPG = 'Role-playing Game'
    OTHER = 'Other'
    GENRES = [
        (SHOOTER, 'Shooter'),
        (ACTION_ADV, 'Action Adventure'),
        (MOBA, 'MOBA'),
        (RACING, 'Racing'),
        (SIM, 'Simulation'),
        (BR, 'Battle Royale'),
        (RTS, 'Real-time Strategy'),
        (PUZZLE_PLAT, 'Puzzle Platform'),
        (SPORTS, 'Sports'),
        (MMO, 'MMO'),
        (SINGLE, 'Singleplayer'),
        (COOP, 'Co-op'),
        (RPG, 'Role-playing Game'),
        (OTHER, 'Other')
    ]
    ALL = 'All Platforms'
    PC = 'PC'
    PS4 = 'PS4'
    PS5 = 'PS5'
    XB1 = 'Xbox One'
    XBX = 'Xbox Series X'
    SWITCH = 'Nintendo Switch'
    OTHER = 'Other'
    GAMING_PLATFORM = [
        (ALL, 'All Platforms'),
        (PC, 'PC'),
        (PS4, 'PS4'),
        (PS5, 'PS5'),
        (XB1, 'Xbox One'),
        (XBX, 'Xbox Series X'),
        (SWITCH, 'Nintendo Switch'),
        (OTHER, 'Other')
    ]
    title = models.CharField(
        max_length=180, unique=True, null=False, blank=False)
    image = CloudinaryField('image', default='placeholder')
    description = models.TextField(null=False, blank=False)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='game_post', null=False)
    genre = models.CharField(max_length=80, choices=GENRES, default=SHOOTER)
    release_date = models.DateField(null=False, blank=False)
    platform = models.CharField(
        max_length=15, choices=GAMING_PLATFORM, default=ALL)
    created_on = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(
        max_length=200, unique=True, null=False, blank=False)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"slug": self.slug})


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.user)

add_game/forms.py
from django import forms
from library.models import Post


class DateInput(forms.DateInput):
    input_type = 'date'


class AddGameForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [
            'title', 'image', 'description', 'genre',
            'platform', 'release_date', 'slug'
            ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'pad'}),
            'image': forms.FileInput(attrs={'class': 'pad'}),
            'description': forms.Textarea(
                attrs={'class': 'pad', 'cols': 45, 'rows': 5}),
            'genre': forms.Select(choices=Post.GENRES, attrs={'class': 'pad'}),
            'platform': forms.Select(
                choices=Post.GAMING_PLATFORM, attrs={'class': 'pad'}),
            'release_date': DateInput(attrs={'class': 'pad'}),
            'slug': forms.HiddenInput(),
        }

add_game/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import AddGameForm
from library.views import library
from library.models import Post


@login_required
def add_game(request):
    if request.method == 'POST':
        form = AddGameForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, "Game successfully added")
            return redirect(library)
        else:
            messages.error(
                request,
                "There was a problem adding this game. Please try again")
    form = AddGameForm()
    template = 'add_game/add_game.html'
    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def update_game(request, id):
    game = get_object_or_404(Post, id=id)
    if not game.user == request.user:
        messages.error(request, "You are not authorised")
        return redirect(library)

    if request.method == 'POST':
        form = AddGameForm(request.POST, request.FILES, instance=game)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, "Game successfully updated")
            return redirect(library)
        else:
            messages.error(
                request,
                "There was a problem updated this game. Please try again")
    form = AddGameForm(instance=game)
    template = 'add_game/update_game.html'
    context = {
        'form': form,
        'game': game,
    }
    return render(request, template, context)


@login_required
def delete_game(request, id):
    game = get_object_or_404(Post, id=id)
    if not game.user == request.user:
        messages.error(request, "You are not authorised")
        return redirect(library)

    messages.success(request, "Game successfully deleted")
    game.delete()
    return redirect(library)

add_game/templates/add_game/add_game.html
{% extends 'base.html' %}

{% block title %}
Gamers Library | Add Games
{% endblock %}

{% block content %}

    <!-- form to add game post to database -->
    <div class="form-center">
        <form id="add-game-form" method="POST">
            <h3 class="form-center">Add a Game</h3>
            <hr>
            {% csrf_token %}
            {{ form.slug }}
            <label class="pad" for="id_title">Game Title:</label> <br> 
            {{ form.title }} <br>
            <label class="pad" for="id_image">Image:</label> <br>
            {{ form.image }} <br>
            <label class="pad" for="id_description">Description:</label> <br>
            {{ form.description }} <br>
            <label class="pad" for="id_genre">Primary Genre:</label>
            {{ form.genre }} <br>
            <label class="pad" for="id_platform">Platform:</label>
            {{ form.platform }} <br>
            <label class="pad" for="id_release_date">Release Date:</label>
            {{ form.release_date }} <br>
            <br>
            <button type="submit" id="submit-btn" class="pad btn-rounded">Add Game</button>
        </form>
    </div>

{% endblock %}

{% block js %}
<script>
    // convert Game title to slug-format on front-end
    let title = document.getElementById("id_title");
    let slug = document.getElementById("id_slug");
    title?.addEventListener("keyup", convertToSlug);
    slug?.addEventListener("keyup", convertToSlug);

    function convertToSlug() {
      slug.value = title.value.toLowerCase()
                 .replace(/ /g, '-')
                 .replace(/[^\w-]+/g, '');
    }
</script>
{% endblock %}

add_game/templates/add_game/update_game.html
{% extends 'base.html' %}

{% block title %}
Gamers Library | Update Games
{% endblock %}

{% block content %}

    <!-- form to add game post to database -->
    <div class="form-center">
        <form id="add-game-form" method="POST" action="{% url 'update_game' game.id %}">
            <h3 class="form-center">Update a Game</h3>
            <hr>
            {% csrf_token %}
            {{ form.slug }}
            <label class="pad" for="id_title">Game Title:</label> <br> 
            {{ form.title }} <br>
            <label class="pad" for="id_image">Image:</label> <br>
            {{ form.image }} <br>
            <label class="pad" for="id_description">Description:</label> <br>
            {{ form.description }} <br>
            <label class="pad" for="id_genre">Primary Genre:</label>
            {{ form.genre }} <br>
            <label class="pad" for="id_platform">Platform:</label>
            {{ form.platform }} <br>
            <label class="pad" for="id_release_date">Release Date:</label>
            {{ form.release_date }} <br>
            <br>
            <button type="submit" id="submit-btn" class="pad btn-rounded">Update Game</button>
        </form>
    </div>

{% endblock %}

{% block js %}
<script>
    // convert Game title to slug-format on front-end
    let title = document.getElementById("id_title");
    let slug = document.getElementById("id_slug");
    title?.addEventListener("keyup", convertToSlug);
    slug?.addEventListener("keyup", convertToSlug);

    function convertToSlug() {
      slug.value = title.value.toLowerCase()
                 .replace(/ /g, '-')
                 .replace(/[^\w-]+/g, '');
    }
</script>
{% endblock %}